from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_drone_controller(object):
    def setupUi(self, drone_controller):
        drone_controller.setObjectName("drone_controller")
        drone_controller.resize(500, 600)
        self.forward_btn = QtWidgets.QPushButton(drone_controller)
        self.forward_btn.setGeometry(QtCore.QRect(90, 380, 50, 50))
        self.forward_btn.setObjectName("forward_btn")
        self.left_btn = QtWidgets.QPushButton(drone_controller)
        self.left_btn.setGeometry(QtCore.QRect(40, 430, 50, 50))
        self.left_btn.setObjectName("left_btn")
        self.right_btn = QtWidgets.QPushButton(drone_controller)
        self.right_btn.setGeometry(QtCore.QRect(140, 430, 50, 50))
        self.right_btn.setObjectName("right_btn")
        self.stop_btn = QtWidgets.QPushButton(drone_controller)
        self.stop_btn.setGeometry(QtCore.QRect(90, 430, 50, 50))
        self.stop_btn.setObjectName("stop_btn")
        self.back_btn = QtWidgets.QPushButton(drone_controller)
        self.back_btn.setGeometry(QtCore.QRect(90, 480, 50, 50))
        self.back_btn.setObjectName("back_btn")
        self.tracking_btn = QtWidgets.QPushButton(drone_controller)
        self.tracking_btn.setGeometry(QtCore.QRect(380, 420, 100, 50))
        self.tracking_btn.setObjectName("tracking_btn")
        
        # self.drone_cam = QtWidgets.QGraphicsView(drone_controller)
        # self.drone_cam.setGeometry(QtCore.QRect(10, 10, 480, 320))
        # self.drone_cam.setObjectName("drone_cam")

        self.drone_cam_label = QtWidgets.QLabel(drone_controller)
        self.drone_cam_label.setGeometry(QtCore.QRect(10, 10, 480, 320))
        self.drone_cam_label.setObjectName("drone_cam_label")
        # (선택) QLabel에 배경색이나 정렬, 기타 속성을 주고 싶으면 설정
        self.drone_cam_label.setStyleSheet("background-color: black;")
        self.drone_cam_label.setAlignment(QtCore.Qt.AlignCenter)
        
        self.speed_up_btn = QtWidgets.QPushButton(drone_controller)
        self.speed_up_btn.setGeometry(QtCore.QRect(220, 390, 70, 50))
        self.speed_up_btn.setObjectName("speed_up_btn")
        self.speed_down_btn = QtWidgets.QPushButton(drone_controller)
        self.speed_down_btn.setGeometry(QtCore.QRect(220, 450, 70, 50))
        self.speed_down_btn.setObjectName("speed_down_btn")
        self.land_btn = QtWidgets.QPushButton(drone_controller)
        self.land_btn.setGeometry(QtCore.QRect(300, 450, 70, 50))
        self.land_btn.setObjectName("land_btn")
        self.tackoff_btn = QtWidgets.QPushButton(drone_controller)
        self.tackoff_btn.setGeometry(QtCore.QRect(300, 390, 70, 50))
        self.tackoff_btn.setObjectName("tackoff_btn")
        self.rotate_left_btn = QtWidgets.QPushButton(drone_controller)
        self.rotate_left_btn.setGeometry(QtCore.QRect(40, 380, 50, 50))
        self.rotate_left_btn.setObjectName("rotate_left_btn")
        self.rotate_right_btn = QtWidgets.QPushButton(drone_controller)
        self.rotate_right_btn.setGeometry(QtCore.QRect(140, 380, 50, 50))
        self.rotate_right_btn.setObjectName("rotate_right_btn")
        self.label = QtWidgets.QLabel(drone_controller)
        self.label.setGeometry(QtCore.QRect(280, 555, 120, 30))
        self.label.setObjectName("label")
        self.linear_text = QtWidgets.QLabel(drone_controller)
        self.linear_text.setGeometry(QtCore.QRect(280, 525, 100, 30))
        self.linear_text.setObjectName("linear_text")
        self.linear_lcd = QtWidgets.QLCDNumber(drone_controller)
        self.linear_lcd.setGeometry(QtCore.QRect(410, 530, 64, 23))
        self.linear_lcd.setObjectName("linear_lcd")
        self.angular_lcd = QtWidgets.QLCDNumber(drone_controller)
        self.angular_lcd.setGeometry(QtCore.QRect(410, 560, 64, 23))
        self.angular_lcd.setObjectName("angular_lcd")
        self.rise_btn = QtWidgets.QPushButton(drone_controller)
        self.rise_btn.setGeometry(QtCore.QRect(40, 480, 50, 50))
        self.rise_btn.setObjectName("rise_btn")
        self.fall_btn = QtWidgets.QPushButton(drone_controller)
        self.fall_btn.setGeometry(QtCore.QRect(140, 480, 50, 50))
        self.fall_btn.setObjectName("fall_btn")

        self.retranslateUi(drone_controller)
        QtCore.QMetaObject.connectSlotsByName(drone_controller)

    def retranslateUi(self, drone_controller):
        _translate = QtCore.QCoreApplication.translate
        drone_controller.setWindowTitle(_translate("drone_controller", "drone_controller_window"))
        self.forward_btn.setText(_translate("drone_controller", "∧"))
        self.left_btn.setText(_translate("drone_controller", "<"))
        self.right_btn.setText(_translate("drone_controller", ">"))
        self.stop_btn.setText(_translate("drone_controller", "-"))
        self.back_btn.setText(_translate("drone_controller", "∨"))
        self.tracking_btn.setText(_translate("drone_controller", "Tracking"))
        self.speed_up_btn.setText(_translate("drone_controller", "speed ∧"))
        self.speed_down_btn.setText(_translate("drone_controller", "speed ∨"))
        self.land_btn.setText(_translate("drone_controller", "land"))
        self.tackoff_btn.setText(_translate("drone_controller", "tackoff"))
        self.rotate_left_btn.setText(_translate("drone_controller", "↺"))
        self.rotate_right_btn.setText(_translate("drone_controller", "↻"))
        self.label.setText(_translate("drone_controller", "angular velocity"))
        self.linear_text.setText(_translate("drone_controller", "linear velocity"))
        self.rise_btn.setText(_translate("drone_controller", "↑"))
        self.fall_btn.setText(_translate("drone_controller", "↓"))

